# Generated by Django 4.0.2 on 2022-02-11 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jurms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
