# Generated by Django 4.0.2 on 2022-02-18 11:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Admin'), (2, 'Prof'), (3, 'Student')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dept_code', models.CharField(max_length=100, unique=True)),
                ('dept_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_hod', models.CharField(blank=True, max_length=100)),
                ('dept_hod_email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_pic', models.FileField(default='/media/prof/user.png', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prof_dept', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='juphd_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_pic', models.FileField(default='/media/student/user.png', upload_to='')),
                ('student_date_of_reg', models.DateField(blank=True, null=True)),
                ('index_no', models.CharField(max_length=12, unique=True)),
                ('student_category', models.CharField(blank=True, max_length=100)),
                ('student_scholarship', models.CharField(blank=True, max_length=100)),
                ('title_of_thesis', models.CharField(blank=True, max_length=200)),
                ('pre_thesis_submission_date', models.DateField(blank=True, null=True)),
                ('defence', models.DateField(blank=True, null=True)),
                ('thesis_review_paper_1', models.FileField(blank=True, null=True, upload_to='')),
                ('thesis_review_paper_2', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prof_under', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juphd_app.prof')),
                ('student_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juphd_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('student_result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_result_paper_1_number', models.CharField(blank=True, max_length=100)),
                ('student_result_paper_2_number', models.CharField(blank=True, max_length=100)),
                ('student_result_created_at', models.DateTimeField(auto_now_add=True)),
                ('student_result_updated_at', models.DateTimeField(auto_now=True)),
                ('student_result_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juphd_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_pic', models.FileField(default='/media/admin/user.png', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
