# Generated by Django 4.0.2 on 2022-02-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juphd_app', '0002_department_dept_faculty_prof_prof_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_scholarship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
