# Generated by Django 4.0.2 on 2022-02-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juphd_app', '0003_alter_student_student_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='defence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pre_thesis_submission_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_date_of_reg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
