# Generated by Django 4.0.2 on 2022-02-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juphd_app', '0004_alter_student_defence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default='/media/student/user.png', max_length=300, upload_to=''),
        ),
    ]
