# Generated by Django 4.0.2 on 2022-02-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juphd_app', '0007_remove_student_examiner_panel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='examiner_panel_1_phone',
            new_name='examiner_panel_1_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='examiner_panel_2_phone',
            new_name='examiner_panel_2_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='examiner_panel_3_phone',
            new_name='examiner_panel_3_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='examiner_panel_4_phone',
            new_name='examiner_panel_4_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='examiner_panel_5_phone',
            new_name='examiner_panel_5_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='examiner_panel_6_phone',
            new_name='examiner_panel_6_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='viva_expert_1_phone',
            new_name='viva_expert_1_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='viva_expert_2_phone',
            new_name='viva_expert_2_number',
        ),
    ]
