# Generated by Django 4.0.2 on 2022-02-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juphd_app', '0008_rename_examiner_panel_1_phone_student_examiner_panel_1_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_changed_title_of_thesis',
            field=models.BooleanField(default=False),
        ),
    ]
